name: Dart CI

#os:
#  - osx
#install:
#  - git clone https://github.com/flutter/flutter.git
#  - export PATH="$PATH:`pwd`/flutter/bin"
#script:
#  - flutter doctor && flutter test


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
#  install:
#    - git clone https://github.com/flutter/flutter.git
#    - export PATH="PATH:`pwd`/flutter/bin"
  build:
    runs-on: ubuntu-latest

#    container:
#      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
