name: Dart CI

#os:
#  - osx
#install:
#  - git clone https://github.com/flutter/flutter.git
#  - export PATH="$PATH:`pwd`/flutter/bin"
#script:
#  - flutter doctor && flutter test


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
#  install:
#    - git clone https://github.com/flutter/flutter.git
#    - export PATH="PATH:`pwd`/flutter/bin"
  build:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter test
